kind: pipeline
name: default
steps:
- name: test
  image: golang:1.12.5-stretch
  commands:
  - go test -v

- name: build
  image: golang:1.12.5-stretch
  commands:
  - go mod download
  - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o release/kongdesk .
  - echo -n "latest,$${DRONE_COMMIT}" > .tags
  - "[ -z \"$$DRONE_TAG\" ] && echo \"No release tag found\" || echo -n \",$$DRONE_TAG\" >> .tags"
  when:
    branch:
      exclude:
      - master
    event:
    - push
    - pull request
    - tag

- name: publish
  image: plugins/docker
  settings:
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: kongdesk/web
  when:
    branch:
      exclude:
      - master
    event:
    - push
    - tag
