version: "3.5"
services:
  exp:
    image: kongdesk/web
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.exp.rule=Host(`exp.apisdesk.com`) || (Host(`exp.apisdesk.com`) && Path(`/v1`))"
        - "traefik.http.routers.exp.entrypoints=web-secure"
        - "traefik.http.routers.exp.tls.certresolver=apisdesk"
        - "traefik.http.services.exp.loadbalancer.server.port=8080"

networks:
  traefik-public:
    external: true